In [3]:
import torch
import numpy as np


In [3]:
x = torch.Tensor([[1,2,3, 4],[5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16] ])
y = torch.Tensor([[16, 15, 14, 13], [12, 11, 10, 9], [8, 7, 6, 5], [4, 3, 2,1] ])
x.size()

torch.Size([4, 4])

In [4]:
x.shape

torch.Size([4, 4])

In [5]:
x[1]

tensor([5., 6., 7., 8.])

In [6]:
x[0, 0]
x+10


tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.],
        [23., 24., 25., 26.]])

In [7]:
x**2
x+y
torch.exp(x)

y[y>4]

tensor([16., 15., 14., 13., 12., 11., 10.,  9.,  8.,  7.,  6.,  5.])

In [8]:
y2 = x
y2[0, 0]= 1000
print(x)
print(y2)
x = torch.Tensor([[1,2,3, 4],[5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16] ])

y2 = x.clone()
y2[0, 0] = 1000
print(x)
print(y2)

print(x.dtype)
x = x.double()
print(x.dtype)

x = x.int()
print(x)
print(x.dtype)

tensor([[1000.,    2.,    3.,    4.],
        [   5.,    6.,    7.,    8.],
        [   9.,   10.,   11.,   12.],
        [  13.,   14.,   15.,   16.]])
tensor([[1000.,    2.,    3.,    4.],
        [   5.,    6.,    7.,    8.],
        [   9.,   10.,   11.,   12.],
        [  13.,   14.,   15.,   16.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[1000.,    2.,    3.,    4.],
        [   5.,    6.,    7.,    8.],
        [   9.,   10.,   11.,   12.],
        [  13.,   14.,   15.,   16.]])
torch.float32
torch.float64
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]], dtype=torch.int32)
torch.int32


In [4]:
import numpy as np

x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
print(x.dtype)
x = torch.from_numpy(x)

print(x.dtype)

x = torch.rand([2000,3000])


int64
torch.int64


In [5]:
torch.cuda.is_available()
torch.device('cuda:0')

device(type='cuda', index=0)

In [ ]:
torch.device("cpu")

In [6]:

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
print(device)

cuda:0


In [7]:
x_cuda = x.to(device)
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 1.58 ms, sys: 1.27 ms, total: 2.85 ms
Wall time: 21 ms


In [8]:
%time y = (x - x +x ** 10) **2

CPU times: user 69.3 ms, sys: 34.3 ms, total: 104 ms
Wall time: 113 ms
